# Generated by Django 5.0.3 on 2024-07-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_linkedin_menteeprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='session_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='video_call_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
