# Generated by Django 5.0.3 on 2024-07-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_mentorprofile_session_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='session_duration',
        ),
    ]
