# Generated by Django 5.0.3 on 2024-07-31 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
