# Generated by Django 5.0.3 on 2024-08-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
