# Generated by Django 5.0.3 on 2024-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_booking_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_session',
            name='status',
            field=models.CharField(default='pending', max_length=20),
            preserve_default=False,
        ),
    ]
