# Generated by Django 5.0.3 on 2024-08-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0009_booking_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
